id: P004638
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:45:54.534722
source_metadata:
  id: bdr:W20485
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    62a33e6b60564421a25eeba63cac569b:
      image_group_id: I1KG18821
      title: ''
      volume_number: 1
      total_pages: 758
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
